# Generated by Django 5.2.17 on 2026-08-28 12:21

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_reference', models.CharField(db_column='order_reference', max_length=255, unique=True)),
                ('total_amount', models.DecimalField(db_column='total_amount', decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('payment_status', models.CharField(db_column='payment_status', default='pending', max_length=50)),
                ('intasend_tracking_id', models.CharField(blank=True, db_column='intasend_tracking_id', max_length=255, null=True)),
                ('customer_email', models.CharField(blank=True, db_column='customer_email', max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, db_column='customer_phone', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=255)),
                ('grind', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('tasting_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), db_column='tasting_notes', size=None)),
                ('details', models.TextField()),
                ('is_kes', models.BooleanField(db_column='is_kes', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255)),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_column='last_name', max_length=255, null=True)),
                ('role', models.CharField(default='Customer', max_length=50)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_column='product_id', max_length=255)),
                ('product_name', models.CharField(db_column='product_name', max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(db_column='unit_price', decimal_places=2, max_digits=10)),
                ('grind', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(db_column='payment_method', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('transaction_id', models.CharField(blank=True, db_column='transaction_id', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.order')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(db_column='original_name', max_length=255)),
                ('storage_name', models.CharField(db_column='storage_name', max_length=255)),
                ('storage_path', models.CharField(db_column='storage_path', max_length=255)),
                ('mime_type', models.CharField(db_column='mime_type', max_length=255)),
                ('size', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('is_public', models.BooleanField(db_column='is_public', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='api.user')),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('grind', models.CharField(default='', max_length=255)),
                ('size', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.user')),
            ],
            options={
                'db_table': 'cart_items',
                'unique_together': {('user', 'product', 'grind', 'size')},
            },
        ),
    ]
